name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: ssrv
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.22.3
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build
        run: >
          sudo sh -c 'curl -L https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz -o /tmp/upx-4.2.4-amd64_linux.tar.xz && \
                      tar -xvf /tmp/upx-4.2.4-amd64_linux.tar.xz -C /tmp/ && \
                      mv -f /tmp/upx-4.2.4-amd64_linux/upx /bin/upx && \
                      chmod +x /bin/upx';
          env WITH_UPX=1 CREATE_RELEASE_ARCHIVES=1 sh -c './build.sh all && cd tls && ./build.sh all';

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ssrv*.tar.zst
            tls/ssrv*.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
