name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: shellsrv
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.21.6
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Build
        run: >
          sudo sh -c 'curl -LO https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz && \
                      tar -xvf upx-4.2.2-amd64_linux.tar.xz && \
                      mv -f upx-4.2.2-amd64_linux/upx /bin/upx && \
                      chmod +x /bin/upx';
          env WITH_UPX=1 CREATE_RELEASE_ARCHIVES=1 ./build.sh all;

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: shellsrv*.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
